import Mathlib.Analysis.Convex.Function
import Mathlib.Analysis.SpecialFunctions.Log.Basic
import Mathlib.Order.Filter.Extr
import Mathlib.Topology.MetricSpace.Pseudo.Pi
import Standalone.M2ScoreAccounting

/-!
# Claim 011: M3 admits optimal finite policies and an attained continuation representation

Statement only; the proof is `Novel/M3FiniteContinuationProof.lean`.

M3 (`model/SPEC.md`) is formalized here from its definitions, reusing claim 003's M2 return and
cost objects: `ret` (instrument returns `r_i(θ, s)`), `cost` (the dollar switching cost `C`),
`W0` (`W₀⁻ = h₀⁻ + Σ x₀⁻`), and the scenario law `q`. Dollar initial holdings and cash are the
data's `x0` and `h0`; the data's `gamma` and `wbar` play no role (M3 has no position caps). A
model instance bundles the data with the parameter support `par : T → Params`, the prior `pi0` and
the utility coefficient `rho`. Counts are arbitrary: `n` ETFs, `K` factors (M3's `n ∈ {1, 2}`,
`K = 2` are special cases).

The public first-quarter observation is `obs θ s₀ = (f(θ, s₀), r(θ, s₀))`: the factor realization
and every instrument's return. `Y` is the finite set of such observations. A policy is a root
dollar trade `u₀` and one dollar trade `u₁(y)` per `y ∈ Y`, so it cannot distinguish hidden
`(θ, s₀)` pairs with the same observation. `Cls` labels the classes F (full), E (ETF-only,
`u_A = 0`) and N (no trade).
-/

namespace Standalone.M3FiniteContinuation

open Matrix Standalone.M2ScoreAccounting
open scoped Classical

/-- An M3 instance: the return/cost/initial-position data, parameter support, prior and `ρ`. -/
structure M3 (n K : ℕ) (S T : Type) where
  D : Data 1 n K S
  par : T → Params 1 K
  pi0 : T → ℝ
  rho : ℝ

variable {n K : ℕ} {S T : Type} [Fintype S] [Fintype T]

/-- The public observation type: factor realization and all instrument returns. -/
abbrev Obs (n K : ℕ) := (Fin K → ℝ) × (Inst 1 n → ℝ)

/-- The observation generated by `(θ, s₀)`. -/
def obs (P : M3 n K S T) (t : T) (s : S) : Obs n K :=
  ((P.par t).lam + P.D.zf s, ret P.D (P.par t) s)

/-- The finite set `Y` of possible observations. -/
noncomputable def Yset (P : M3 n K S T) : Finset (Obs n K) :=
  Finset.univ.image fun p : T × S => obs P p.1 p.2

/-- Likelihood `L_θ(y) = Σ_{s : obs θ s = y} q_s`. -/
noncomputable def lik (P : M3 n K S T) (t : T) (y : Obs n K) : ℝ :=
  ∑ s, if obs P t s = y then P.D.q s else 0

/-- Observation probability `P₀(y) = Σ_θ π₀(θ) L_θ(y)`. -/
noncomputable def P0 (P : M3 n K S T) (y : Obs n K) : ℝ := ∑ t, P.pi0 t * lik P t y

/-- Posterior `π₁(θ | y)`, with the prior as bookkeeping when `P₀(y) = 0`. -/
noncomputable def post (P : M3 n K S T) (y : Obs n K) (t : T) : ℝ :=
  if 0 < P0 P y then P.pi0 t * lik P t y / P0 P y else P.pi0 t

/-- Trade classes. -/
inductive Cls
  | F
  | E
  | N

/-- The class restriction on a trade. -/
def Allowed : Cls → (Inst 1 n → ℝ) → Prop
  | .F, _ => True
  | .E, u => u (Sum.inl 0) = 0
  | .N, u => u = 0

/-- Funded feasibility of trade `u` at marked state `(x, h)` in class `c`. -/
def Feas1 (P : M3 n K S T) (c : Cls) (x : Inst 1 n → ℝ) (h : ℝ) (u : Inst 1 n → ℝ) : Prop :=
  (∀ i, 0 ≤ x i + u i) ∧ 0 ≤ h - ∑ i, u i - cost P.D u ∧ Allowed c u

/-- Marked risky holdings at review 1 after root trade `u₀` and observation `y`. -/
def x1 (P : M3 n K S T) (y : Obs n K) (u₀ : Inst 1 n → ℝ) : Inst 1 n → ℝ :=
  fun i => (1 + y.2 i) * (P.D.x0 i + u₀ i)

/-- Cash at review 1 after root trade `u₀`. -/
noncomputable def h1 (P : M3 n K S T) (u₀ : Inst 1 n → ℝ) : ℝ :=
  P.D.h0 - ∑ i, u₀ i - cost P.D u₀

/-- A policy: root trade and one review-1 trade per possible observation. -/
abbrev Policy (P : M3 n K S T) := (Inst 1 n → ℝ) × ((Yset P) → Inst 1 n → ℝ)

/-- The observation of `(θ, s₀)` as an element of `Y`. -/
def obsY (P : M3 n K S T) (t : T) (s : S) : Yset P :=
  ⟨obs P t s, Finset.mem_image.mpr ⟨(t, s), Finset.mem_univ _, rfl⟩⟩

/-- `Π_{D,R}`: root trade in class `d`, every review-1 trade in class `r` at its marked state. -/
def Pol (P : M3 n K S T) (d r : Cls) : Set (Policy P) :=
  {π | Feas1 P d P.D.x0 P.D.h0 π.1 ∧ ∀ y : Yset P, Feas1 P r (x1 P y π.1) (h1 P π.1) (π.2 y)}

/-- Wealth after trade `u` at state `(x, h)`, marked at scenario `s` under parameter `θ`. -/
noncomputable def condW (P : M3 n K S T) (x : Inst 1 n → ℝ) (h : ℝ) (u : Inst 1 n → ℝ) (t : T)
    (s : S) : ℝ :=
  h - ∑ i, u i - cost P.D u + ∑ i, (x i + u i) * (1 + ret P.D (P.par t) s i)

/-- Utility `U_ρ(z) = -exp(-ρ z)`. -/
noncomputable def U (P : M3 n K S T) (z : ℝ) : ℝ := -Real.exp (-P.rho * z)

/-- Marked wealth `W₁⁻` before review 1 on hidden path `(θ, s₀)`. -/
noncomputable def W1m (P : M3 n K S T) (π : Policy P) (t : T) (s₀ : S) : ℝ :=
  h1 P π.1 + ∑ i, x1 P (obs P t s₀) π.1 i

/-- Terminal wealth `W₂` on hidden path `(θ, s₀, s₁)`. -/
noncomputable def W2 (P : M3 n K S T) (π : Policy P) (t : T) (s₀ s₁ : S) : ℝ :=
  condW P (x1 P (obs P t s₀) π.1) (h1 P π.1) (π.2 (obsY P t s₀)) t s₁

/-- The finite expected-terminal-utility sum `Φ`. -/
noncomputable def Phi (P : M3 n K S T) (π : Policy P) : ℝ :=
  ∑ t, ∑ s₀, ∑ s₁, P.pi0 t * P.D.q s₀ * P.D.q s₁ * U P (W2 P π t s₀ s₁ / W0 P.D)

/-- `V_{D,R}`: the supremum of `Φ` over `Π_{D,R}`. -/
noncomputable def V (P : M3 n K S T) (d r : Cls) : ℝ := sSup (Phi P '' Pol P d r)

/-- The review-1 conditional objective at state `(x, h)` and belief `pi`. -/
noncomputable def condObj (P : M3 n K S T) (pi : T → ℝ) (x : Inst 1 n → ℝ) (h : ℝ)
    (u : Inst 1 n → ℝ) : ℝ :=
  ∑ t, ∑ s, pi t * P.D.q s * U P (condW P x h u t s / W0 P.D)

/-- `V₁^R(x, h, π)`. -/
noncomputable def V1 (P : M3 n K S T) (r : Cls) (x : Inst 1 n → ℝ) (h : ℝ) (pi : T → ℝ) : ℝ :=
  sSup (condObj P pi x h '' {u | Feas1 P r x h u})

/-- `H₀^R(u₀) = Σ_{y : P₀(y) > 0} P₀(y) V₁^R(x₁(y; u₀), h₁(u₀), π₁(· | y))`. -/
noncomputable def H0 (P : M3 n K S T) (r : Cls) (u₀ : Inst 1 n → ℝ) : ℝ :=
  ∑ y ∈ Yset P, if 0 < P0 P y then P0 P y * V1 P r (x1 P y u₀) (h1 P u₀) (post P y) else 0

/-- `CE_{D,R} = -(1/ρ) ln(-V_{D,R})`. -/
noncomputable def CE (P : M3 n K S T) (d r : Cls) : ℝ := -(1 / P.rho) * Real.log (-V P d r)

/-- `Δ_R = CE_{F,R} - CE_{E,R}`. -/
noncomputable def Delta (P : M3 n K S T) (r : Cls) : ℝ := CE P .F r - CE P .E r

/-- The M3 restrictions used: `ρ > 0`; scenario and prior masses nonnegative and summing to one;
rates in `[0, 1)`; nonnegative initial holdings and cash with `W₀⁻ > 0`; strictly positive gross
returns at every specified parameter and scenario. -/
def M3Setting (P : M3 n K S T) : Prop :=
  0 < P.rho ∧ (∀ s, 0 ≤ P.D.q s) ∧ ∑ s, P.D.q s = 1 ∧ (∀ t, 0 ≤ P.pi0 t) ∧ ∑ t, P.pi0 t = 1 ∧
  (∀ i, 0 ≤ P.D.kplus i ∧ P.D.kplus i < 1 ∧ 0 ≤ P.D.kminus i ∧ P.D.kminus i < 1) ∧
  (∀ i, 0 ≤ P.D.x0 i) ∧ 0 ≤ P.D.h0 ∧ 0 < W0 P.D ∧ ∀ t s i, 0 < 1 + ret P.D (P.par t) s i

/-- Part 1: for all nine `(D, R)`, `Π_{D,R}` is nonempty, convex and compact; `Φ` is continuous and
concave on it and attains its maximum; marked wealth at review 1 and terminal wealth are strictly
positive on every path; for every bound `M ≥ 1` on all gross returns, `W₁⁻ ≤ M W₀⁻`,
`W₂ ≤ M² W₀⁻` and `-1 < V_{D,R} ≤ -exp(-ρ M²)`. -/
def PolicyAttainment : Prop :=
  ∀ (n K : ℕ) (S T : Type) [Fintype S] [Fintype T] (P : M3 n K S T), M3Setting P →
    ∀ d r : Cls,
      (Pol P d r).Nonempty ∧ Convex ℝ (Pol P d r) ∧ IsCompact (Pol P d r) ∧
      Continuous (Phi P) ∧ ConcaveOn ℝ (Pol P d r) (Phi P) ∧
      (∃ π ∈ Pol P d r, IsMaxOn (Phi P) (Pol P d r) π ∧ Phi P π = V P d r) ∧
      (∀ π ∈ Pol P d r, ∀ t s₀ s₁, 0 < W1m P π t s₀ ∧ 0 < W2 P π t s₀ s₁) ∧
      (∀ M : ℝ, 1 ≤ M → (∀ t s i, 1 + ret P.D (P.par t) s i ≤ M) →
        (∀ π ∈ Pol P d r, ∀ t s₀ s₁, W1m P π t s₀ ≤ M * W0 P.D ∧ W2 P π t s₀ s₁ ≤ M ^ 2 * W0 P.D) ∧
        -1 < V P d r ∧ V P d r ≤ -Real.exp (-P.rho * M ^ 2))

/-- Part 2: for a fixed belief `pi ≥ 0` and nonnegative state, `V₁^R` is attained; it is jointly
concave in `(x, h)` on nonnegative states and nondecreasing in `h`; at `x = h = 0` only the zero
trade is feasible, and the value is `-1` when `pi` sums to one. -/
def ConditionalProblem : Prop :=
  ∀ (n K : ℕ) (S T : Type) [Fintype S] [Fintype T] (P : M3 n K S T), M3Setting P →
    ∀ (r : Cls) (pi : T → ℝ), (∀ t, 0 ≤ pi t) →
      (∀ x h, (∀ i, 0 ≤ x i) → 0 ≤ h →
        ∃ u, Feas1 P r x h u ∧ (∀ u', Feas1 P r x h u' → condObj P pi x h u' ≤ condObj P pi x h u) ∧
          V1 P r x h pi = condObj P pi x h u) ∧
      ConcaveOn ℝ {p : (Inst 1 n → ℝ) × ℝ | (∀ i, 0 ≤ p.1 i) ∧ 0 ≤ p.2}
        (fun p => V1 P r p.1 p.2 pi) ∧
      (∀ x h h', (∀ i, 0 ≤ x i) → 0 ≤ h → h ≤ h' → V1 P r x h pi ≤ V1 P r x h' pi) ∧
      (∀ u, Feas1 P r 0 0 u ↔ u = 0) ∧
      (∑ t, pi t = 1 → V1 P r 0 0 pi = -1)

/-- Part 3: Bayes regrouping (the conditional mass is `π₁(θ | y) q_{s₁}`, and `Φ` is the
`P₀`-weighted sum of conditional objectives at the marked state and posterior); `H₀^R` is concave on
the funded full root set; for every feasible root trade some feasible continuation attains `H₀^R`,
which bounds every continuation; and `V_{D,R} = max Φ = max_{u₀ ∈ D₀} H₀^R(u₀)`, both attained. -/
def ContinuationRepresentation : Prop :=
  ∀ (n K : ℕ) (S T : Type) [Fintype S] [Fintype T] (P : M3 n K S T), M3Setting P →
    (∀ y t, 0 < P0 P y → P.pi0 t * lik P t y = P0 P y * post P y t) ∧
    ∀ d r : Cls,
      (∀ π ∈ Pol P d r, Phi P π = ∑ y : Yset P,
        if 0 < P0 P y then P0 P y * condObj P (post P y) (x1 P y π.1) (h1 P π.1) (π.2 y) else 0) ∧
      ConcaveOn ℝ {u₀ | Feas1 P .F P.D.x0 P.D.h0 u₀} (H0 P r) ∧
      (∀ u₀, Feas1 P d P.D.x0 P.D.h0 u₀ →
        (∃ u₁, (u₀, u₁) ∈ Pol P d r ∧ Phi P (u₀, u₁) = H0 P r u₀) ∧
        ∀ u₁, (u₀, u₁) ∈ Pol P d r → Phi P (u₀, u₁) ≤ H0 P r u₀) ∧
      (∃ u₀, Feas1 P d P.D.x0 P.D.h0 u₀ ∧ H0 P r u₀ = V P d r ∧
        ∀ u₀', Feas1 P d P.D.x0 P.D.h0 u₀' → H0 P r u₀' ≤ V P d r)

/-- Part 4: the value and CE orders over root classes and over continuation classes; `Δ_R ≥ 0`;
and `Δ_R = 0` iff some optimal policy in `Π_{F,R}` has zero active root trade. -/
def ClassComparison : Prop :=
  ∀ (n K : ℕ) (S T : Type) [Fintype S] [Fintype T] (P : M3 n K S T), M3Setting P →
    (∀ r, V P .N r ≤ V P .E r ∧ V P .E r ≤ V P .F r ∧ CE P .N r ≤ CE P .E r ∧ CE P .E r ≤ CE P .F r) ∧
    (∀ d, V P d .N ≤ V P d .E ∧ V P d .E ≤ V P d .F ∧ CE P d .N ≤ CE P d .E ∧ CE P d .E ≤ CE P d .F) ∧
    ∀ r, 0 ≤ Delta P r ∧
      (Delta P r = 0 ↔ ∃ π ∈ Pol P .F r, IsMaxOn (Phi P) (Pol P .F r) π ∧ π.1 (Sum.inl 0) = 0)

/-- Claim 011, all parts. -/
def statement : Prop :=
  PolicyAttainment ∧ ConditionalProblem ∧ ContinuationRepresentation ∧ ClassComparison

end Standalone.M3FiniteContinuation
